[2025-03-22T11:45:58.835+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T11:45:58.840+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transport_dag.extract_bus_stops_task scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T11:45:58.842+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transport_dag.extract_bus_stops_task scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T11:45:58.842+0800] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-22T11:45:58.846+0800] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_bus_stops_task> on 2025-03-21 00:00:00+00:00
[2025-03-22T11:45:58.849+0800] {standard_task_runner.py:72} INFO - Started process 98533 to run task
[2025-03-22T11:45:58.852+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'transport_dag', 'extract_bus_stops_task', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/var/folders/08/pmnk96px7x94djx_0kg9f2zh0000gn/T/tmpyrxvcia_']
[2025-03-22T11:45:58.854+0800] {standard_task_runner.py:105} INFO - Job 19: Subtask extract_bus_stops_task
[2025-03-22T11:45:58.870+0800] {task_command.py:467} INFO - Running <TaskInstance: transport_dag.extract_bus_stops_task scheduled__2025-03-21T00:00:00+00:00 [running]> on host melvins-macbook-pro-2.local
[2025-03-22T11:45:58.893+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='transport_dag' AIRFLOW_CTX_TASK_ID='extract_bus_stops_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-22T11:45:58.893+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T11:47:24.155+0800] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2025-03-22T11:47:24.155+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-22T11:47:24.165+0800] {process_utils.py:132} INFO - Sending 15 to group 98533. PIDs of all processes in the group: [98533]
[2025-03-22T11:47:24.165+0800] {process_utils.py:87} INFO - Sending the signal 15 to group 98533
[2025-03-22T11:48:24.199+0800] {process_utils.py:150} WARNING - process psutil.Process(pid=98533, name='python3.9', status='running', started='11:45:58') did not respond to SIGTERM. Trying SIGKILL
[2025-03-22T11:48:24.199+0800] {process_utils.py:87} INFO - Sending the signal 9 to group 98533
[2025-03-22T11:48:24.203+0800] {process_utils.py:80} INFO - Process psutil.Process(pid=98533, name='python3.9', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='11:45:58') (98533) terminated with exit code -9
[2025-03-22T11:48:24.203+0800] {standard_task_runner.py:190} ERROR - ('Job 19 was killed before it finished (likely due to running out of memory)', 'For more information, see https://airflow.apache.org/docs/apache-airflow/stable/troubleshooting.html#LocalTaskJob-killed')
