[2025-03-22T11:10:08.750+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T11:10:08.755+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transport_dag.transform_bus_data_task manual__2025-03-22T03:09:32.221557+00:00 [queued]>
[2025-03-22T11:10:08.757+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transport_dag.transform_bus_data_task manual__2025-03-22T03:09:32.221557+00:00 [queued]>
[2025-03-22T11:10:08.757+0800] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-22T11:10:08.762+0800] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_bus_data_task> on 2025-03-22 03:09:32.221557+00:00
[2025-03-22T11:10:08.765+0800] {standard_task_runner.py:72} INFO - Started process 93943 to run task
[2025-03-22T11:10:08.768+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'transport_dag', 'transform_bus_data_task', 'manual__2025-03-22T03:09:32.221557+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/var/folders/08/pmnk96px7x94djx_0kg9f2zh0000gn/T/tmpktovcwvj']
[2025-03-22T11:10:08.770+0800] {standard_task_runner.py:105} INFO - Job 160: Subtask transform_bus_data_task
[2025-03-22T11:10:08.785+0800] {task_command.py:467} INFO - Running <TaskInstance: transport_dag.transform_bus_data_task manual__2025-03-22T03:09:32.221557+00:00 [running]> on host melvins-macbook-pro-2.local
[2025-03-22T11:10:08.806+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='transport_dag' AIRFLOW_CTX_TASK_ID='transform_bus_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T03:09:32.221557+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-22T03:09:32.221557+00:00'
[2025-03-22T11:10:08.807+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T11:10:08.991+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 117, in transform_bus_data
    bus_routes = pd.DataFrame(merged_df, columns=["ServiceNo", "Operator", "Direction", "BusStopCode", "RoadName", "Description", "Latitude", "Longitude"])
NameError: name 'merged_df' is not defined
[2025-03-22T11:10:08.996+0800] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=transport_dag, task_id=transform_bus_data_task, run_id=manual__2025-03-22T03:09:32.221557+00:00, execution_date=20250322T030932, start_date=20250322T031008, end_date=20250322T031008
[2025-03-22T11:10:09.002+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T11:10:09.002+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 160 for task transform_bus_data_task (name 'merged_df' is not defined; 93943)
Traceback (most recent call last):
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 117, in transform_bus_data
    bus_routes = pd.DataFrame(merged_df, columns=["ServiceNo", "Operator", "Direction", "BusStopCode", "RoadName", "Description", "Latitude", "Longitude"])
NameError: name 'merged_df' is not defined
[2025-03-22T11:10:09.052+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-22T11:10:09.060+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-22T11:10:09.060+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
