[2025-03-22T08:12:14.205+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T08:12:14.210+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transport_dag.extract_bus_routes_task scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T08:12:14.212+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transport_dag.extract_bus_routes_task scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-22T08:12:14.213+0800] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-22T08:12:14.218+0800] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_bus_routes_task> on 2025-03-21 00:00:00+00:00
[2025-03-22T08:12:14.221+0800] {standard_task_runner.py:72} INFO - Started process 85950 to run task
[2025-03-22T08:12:14.225+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'transport_dag', 'extract_bus_routes_task', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/var/folders/08/pmnk96px7x94djx_0kg9f2zh0000gn/T/tmpr11abrms']
[2025-03-22T08:12:14.226+0800] {standard_task_runner.py:105} INFO - Job 83: Subtask extract_bus_routes_task
[2025-03-22T08:12:14.246+0800] {task_command.py:467} INFO - Running <TaskInstance: transport_dag.extract_bus_routes_task scheduled__2025-03-21T00:00:00+00:00 [running]> on host 192.168.1.64
[2025-03-22T08:12:14.268+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='transport_dag' AIRFLOW_CTX_TASK_ID='extract_bus_routes_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-22T08:12:14.269+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T08:12:32.387+0800] {job.py:229} INFO - Heartbeat recovered after 13.13 seconds
[2025-03-22T08:30:32.525+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 831, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 784, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/http/client.py", line 626, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 857, in read_chunked
    self._original_response.close()
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 33, in extract_bus_routes
    response = requests.get(f"{URL}?$skip={skip}", headers=headers)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))
[2025-03-22T08:30:32.535+0800] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=transport_dag, task_id=extract_bus_routes_task, run_id=scheduled__2025-03-21T00:00:00+00:00, execution_date=20250321T000000, start_date=20250322T001214, end_date=20250322T003032
[2025-03-22T08:30:32.543+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T08:30:32.543+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 83 for task extract_bus_routes_task (("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer')); 85950)
Traceback (most recent call last):
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 444, in _error_catcher
    yield
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 831, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 784, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/http/client.py", line 626, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/models.py", line 820, in generate
    yield from self.raw.stream(chunk_size, decode_content=True)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 624, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 857, in read_chunked
    self._original_response.close()
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/response.py", line 461, in _error_catcher
    raise ProtocolError("Connection broken: %r" % e, e)
urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 33, in extract_bus_routes
    response = requests.get(f"{URL}?$skip={skip}", headers=headers)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/sessions.py", line 746, in send
    r.content
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/models.py", line 902, in content
    self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/models.py", line 822, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(54, 'Connection reset by peer')", ConnectionResetError(54, 'Connection reset by peer'))
[2025-03-22T08:30:32.655+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-22T08:30:32.665+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-22T08:30:32.666+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-22T10:36:31.671+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T10:36:31.674+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transport_dag.extract_bus_routes_task scheduled__2025-03-21T00:00:00+00:00 [up_for_retry]>
[2025-03-22T10:36:31.676+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transport_dag.extract_bus_routes_task scheduled__2025-03-21T00:00:00+00:00 [up_for_retry]>
[2025-03-22T10:36:31.676+0800] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-22T10:36:31.680+0800] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_bus_routes_task> on 2025-03-21 00:00:00+00:00
[2025-03-22T10:36:31.683+0800] {standard_task_runner.py:72} INFO - Started process 88340 to run task
[2025-03-22T10:36:31.686+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'transport_dag', 'extract_bus_routes_task', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/var/folders/08/pmnk96px7x94djx_0kg9f2zh0000gn/T/tmphd7q_g5i']
[2025-03-22T10:36:31.688+0800] {standard_task_runner.py:105} INFO - Job 86: Subtask extract_bus_routes_task
[2025-03-22T10:36:31.703+0800] {task_command.py:467} INFO - Running <TaskInstance: transport_dag.extract_bus_routes_task scheduled__2025-03-21T00:00:00+00:00 [running]> on host melvins-macbook-pro-2.local
[2025-03-22T10:36:31.722+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='transport_dag' AIRFLOW_CTX_TASK_ID='extract_bus_routes_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-22T10:36:31.722+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T10:36:37.070+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-22T10:36:37.093+0800] {process_utils.py:132} INFO - Sending 15 to group 88340. PIDs of all processes in the group: [88340]
[2025-03-22T10:36:37.094+0800] {process_utils.py:87} INFO - Sending the signal 15 to group 88340
[2025-03-22T10:36:37.094+0800] {taskinstance.py:3094} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-22T10:36:37.096+0800] {taskinstance.py:3095} ERROR - Stacktrace: 
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/__main__.py", line 62, in main
    args.func(args)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 33, in extract_bus_routes
    response = requests.get(f"{URL}?$skip={skip}", headers=headers)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3095, in signal_handler
    self.log.error("Stacktrace: \n%s", "".join(traceback.format_stack()))

[2025-03-22T10:36:37.098+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/airflow/dags/main.py", line 33, in extract_bus_routes
    response = requests.get(f"{URL}?$skip={skip}", headers=headers)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/connectionpool.py", line 716, in urlopen
    httplib_response = self._make_request(
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/urllib3/connectionpool.py", line 463, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/melvinang/.pyenv/versions/3.9.18/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Users/melvinang/Documents/NUS/Y3S2/IS3107/transport_project/IS3107-Group-8/local_airflow/.airflow/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3097, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-03-22T10:36:37.100+0800] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=transport_dag, task_id=extract_bus_routes_task, run_id=scheduled__2025-03-21T00:00:00+00:00, execution_date=20250321T000000, start_date=20250322T023631, end_date=20250322T023637
[2025-03-22T10:36:37.111+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
